"""add household is_active

Revision ID: dc63aa5d7ba7
Revises: 3c8c1e6dcff0
Create Date: 2026-07-08 06:24:51.370349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc63aa5d7ba7'
down_revision = '3c8c1e6dcff0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('households', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('households', 'is_active')
    # ### end Alembic commands ###
