"""add audit_logs table

Revision ID: f093efe8ef19
Revises: 6f900ce6a7ff
Create Date: 2026-07-07 06:34:24.336188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f093efe8ef19'
down_revision = '6f900ce6a7ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
